name: redis-stack

services:
  redis_stack:
    container_name: redis_stack
    image: redis/redis-stack:latest
    restart: on-failure:3
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - ./tmp/redis_data:/data
